/**
 * Validation at the HTTP boundary, and nowhere else.
 *
 * Everything arriving from a browser is untrusted and shapeless. These helpers
 * turn it into the narrow types the rest of the app already assumes, and throw
 * an HttpError with a usable status when it does not fit. Internal callers
 * stay free of defensive checks.
 */
export class HttpError extends Error {
  constructor(readonly status: number, message: string) {
    super(message);
  }
}

/** Ids are generated by src/db/connection.ts as `<prefix>_<base36>`. */
const ID = /^[a-z]{2,6}_[a-z0-9]{8,32}$/;
const KEY = /^[a-z][a-z0-9_]{1,63}$/;

export function idParam(source: unknown, prefix: string, label: string): string {
  const value = (source as Record<string, unknown> | undefined)?.id;
  if (typeof value !== 'string' || !ID.test(value) || !value.startsWith(`${prefix}_`)) {
    throw new HttpError(404, `No such ${label}.`);
  }
  return value;
}

export const clientIdParam = (source: unknown) => idParam(source, 'cli', 'client');
export const packIdParam = (source: unknown) => idParam(source, 'pack', 'evidence pack');

export function requiredText(source: unknown, field: string, label: string, max = 200): string {
  const value = (source as Record<string, unknown> | undefined)?.[field];
  if (typeof value !== 'string' || value.trim() === '') {
    throw new HttpError(400, `${label} is required.`);
  }
  const trimmed = value.trim();
  if (trimmed.length > max) throw new HttpError(400, `${label} must be ${max} characters or fewer.`);
  return trimmed;
}

export function optionalText(source: unknown, field: string, max = 200): string | null {
  const value = (source as Record<string, unknown> | undefined)?.[field];
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  if (trimmed === '') return null;
  if (trimmed.length > max) throw new HttpError(400, `"${field}" must be ${max} characters or fewer.`);
  return trimmed;
}

export function optionalCount(source: unknown, field: string, max = 1_000_000): number | null {
  const value = (source as Record<string, unknown> | undefined)?.[field];
  if (typeof value !== 'string' || value.trim() === '') return null;
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < 0 || parsed > max) {
    throw new HttpError(400, `"${field}" must be a whole number between 0 and ${max}.`);
  }
  return parsed;
}

export function configKey(value: unknown, label: string): string {
  if (typeof value !== 'string' || !KEY.test(value)) {
    throw new HttpError(400, `Unrecognised ${label}.`);
  }
  return value;
}

/** Form checkbox groups arrive as a string, an array, or not at all. */
export function keyList(source: unknown, field: string, label: string, max = 50): string[] {
  const raw = (source as Record<string, unknown> | undefined)?.[field];
  if (raw === undefined) return [];
  const values = Array.isArray(raw) ? raw : [raw];
  if (values.length > max) throw new HttpError(400, `Too many ${label} values.`);
  return values.map((value) => configKey(value, label));
}
